# **Introduction to Computer Vision**

## What is Computer Vision?

![cars_example](http://hdgreetings.typepad.com/.a/6a00e54fc3203e883401b7c7a84e63970b-800wi "Cars Example")

Computer vision is the process that allows for computers to have a high level understanding of information from images or videos. "High level understanding" means more than simply the data that makes up an image or video. It means to understand what is going on in the image. Is there a car? Is it facing toward or away from the camera? If it is a video, what is the speed of the car?

## Installing

For robomasters, we will primarily be using [OpenCV](https://opencv.org/). OpenCV stands for open source computer vision and it is a great choice for all levels of computer vision applications. It works on almost any platform and has interfaces available for Python, C++, and Java. You may use which ever language you are most comfortable with for robomasters work, but Python will be used for demonstrations and guides.

For Python, the easist way to install OpenCV is with `pip`, a package manager for Python. Depending on your setup, you may need to use `pip3` instead. To install OpenCV with `pip` enter the following command:

`pip install opencv-python`

To check if OpenCV installed, start the Python 3 repl in your terminal, by entering either `python` or `python3`. Then in the repl enter:

`import cv2`

Next enter:

`print(cv2.__version__)`

If "3.X.X" is printed you have successfully installed OpenCV. Congratulations.

## Getting Started

In almost all of your OpenCV programs you will need the first two lines to be as shown below:

In [61]:
import cv2
import numpy as np
import imutils

We already know that `cv2` refers to the OpenCV library. The second import, called `numpy`, is a scientific computing package.

## Displaying an Image

Displaying an image with OpenCV is very simple. It requies four basic functions. The first `imread` does exactly what it sounds like. It reads an image located somewhere on your computer. For the first example `image_1.png` will be used. It is located in the same directory as this one. If you want to view the image you can open it within Jupyter Lab by simply double clicking on it in the directory. The cell below demonstrates how to declare an image for use with OpenCV.

In [2]:
img = cv2.imread('image_1.png')

If the `type` of `img` is printed, we can see that `img` is in fact simply an `numpy` type called an `ndarray` standing for n-dimensional array. We can then print `img` variable itself and see that is simply a three dimensional array as shown below.

In [3]:
print(type(img))
print(img)

<class 'numpy.ndarray'>
[[[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [255 255 255]
  ...
  [255 255 255]
  [  0   0   0]
  [  0   0   0]]

 ...

 [[  0   0   0]
  [  0   0   0]
  [255 255 255]
  ...
  [255 255 255]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]

 [[  0   0   0]
  [  0   0   0]
  [  0   0   0]
  ...
  [  0   0   0]
  [  0   0   0]
  [  0   0   0]]]


Obviously this is a huge array, so it is not very helpful to print the whole array at once. Instead let's print just a single pixel from the image at point (50,50). For dealing with images, point (0,0) is the upper left corner of the image. The resulting array is of length three and shows the color values for the pixel at that coordinate in BGR (blue, green, red) format. This is what an image is made up of. It is simply multidimensional array of pixel values.

In [4]:
print(img[50][50])

[ 62 148  43]


To actually show the image, two more functions are needed. `imshow` shows the image and takes the name of the window and the image (remember an image is just an `ndarray`). The second function isn't as obvious. It is called `waitKey` and it allows you to designate the amount of time you wish for the image to show in milliseconds. In the case of this program the function is given a 0 which means that it will wait infinite time until a key is pressed.

The last function in the cell below simply closes all windows. Execute the cell below, and press any key to destroy the window. You can mouse to coordinates (50,50) on the image and see if it lines up with the BGR value that you saw above.

In [5]:
cv2.imshow('image', img) # show the image
cv2.waitKey(0) # wait until any key is pressed
cv2.destroyAllWindows() # destroy all windows

## Converting Images

Coverting images to different color schemes is very important to manipulating and isolating important parts of images. Below is a simply color conversion that converts a color image (BGR) to grayscale. It uses the the `cvtColor` function to achieve this which takes the original image as the first paramater and a constant `COLOR_BGR2GRAY`.

In [6]:
gray_image = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

Recall that the cell below is the same as the cell a couple cells above simply with `img` swapped with `gray_image`. Execute it to display the now grayscale image.

In [7]:
cv2.imshow('image', gray_image) # show the image
cv2.waitKey(0) # wait until any key is pressed
cv2.destroyAllWindows() # destroy all windows

One of the most important conversions that you will often need to make is the conversion to HSV. HSV stands for "hue, saturation, value" and is represented by the graphic below.

![hsv](https://i.pinimg.com/originals/9d/db/c1/9ddbc1080e2b85241ebf04b3b27cfa0a.png)

When working with computervision it is often desired to convert images to HSV due to the increased ease in segmenting the color values. Observe the example below.

Here we use a new image of a car from behind. The first cell below displays the image in standard BGR.

In [8]:
car_img = cv2.imread('car.jpg')
cv2.imshow('image', car_img) # show the image
cv2.waitKey(0) # wait until any key is pressed
cv2.destroyAllWindows() # destroy all windows

However, in the cell below, the image is converted to HSV. Notice how the headlights are seperated from the rest of the image.

In [9]:
hsv_image = cv2.cvtColor(car_img, cv2.COLOR_BGR2HSV)
cv2.imshow('image', hsv_image) # show the image
cv2.waitKey(0) # wait until any key is pressed
cv2.destroyAllWindows() # destroy all windows

## Isolate Elements
Now that we have converted the image to a more desireable color system, it is time to actually try separating the important elements from the background. To do this we will define a range of values to look for in the image. In OpenCV, hue ranges from 0 to 179, while saturation and value range from 0 to 255. To isolate important elements we will simply define a range of these values to isolate. Observe the example below with the car image again.

In [49]:
lower_1 = np.array([0,30,0]) # define lower hsv range
upper_1 = np.array([10,255,255])# define upper hsv range
mask_1 = cv2.inRange(hsv_image, lower_1, upper_1)# define a mask using the range

lower_2 = np.array([160,0,0]) # define lower hsv range
upper_2 = np.array([179,255,255])# define upper hsv range
mask_2 = cv2.inRange(hsv_image, lower_2, upper_2)# define a mask using the range
        
headlights_1 = cv2.bitwise_and(hsv_image, hsv_image, mask=mask_1) # bitwise and the using the mask

headlights_2 = cv2.bitwise_and(hsv_image, hsv_image, mask=mask_2)

result = headlights_1+headlights_2

cv2.imshow('image', result) # show the image
cv2.waitKey(0) # wait until any key is pressed
cv2.destroyAllWindows() # destroy all windows

## Blur
The next step is to blur the result from isolating the elements we want. It's very hard to achieve a perfect isolation of the elements that we want, so to improve our isolation we use a blur. Which requires us first to convert back to BGR.

In [50]:
bgr_headlights = cv2.cvtColor(result, cv2.COLOR_HSV2BGR)
blurred_headlights = cv2.GaussianBlur(bgr_headlights, (5,5), 0)    
cv2.imshow('Blurred', blurred_headlights)
cv2.waitKey(0) # wait until any key is pressed
cv2.destroyAllWindows() # destroy all windows

## Thresholding
Thresholding means to convert the pixels in an image to a consistent color if it is above a certain value and to another color if it is below a certain value. See below.

In [132]:
thresh = cv2.threshold(blurred_headlights, 60, 255, cv2.THRESH_BINARY)[1]
cv2.imshow('Threshold', thresh)
cv2.waitKey(0) # wait until any key is pressed
cv2.destroyAllWindows() # destroy all windows

## Detecting Shapes

In [133]:
def detect(c):
        # initialize the shape name and approximate the contour
        shape = "unidentified"
        peri = cv2.arcLength(c, True)
        approx = cv2.approxPolyDP(c, 0.06 * peri, True)
        # if the shape is a triangle, it will have 3 vertices
        if len(approx) == 3:
            shape = "triangle"
 
        # if the shape has 4 vertices, it is either a square or
        # a rectangle
        elif len(approx) == 4:
            # compute the bounding box of the contour and use the
            # bounding box to compute the aspect ratio
            (x, y, w, h) = cv2.boundingRect(approx)
            ar = w / float(h)
 
            # a square will have an aspect ratio that is approximately
            # equal to one, otherwise, the shape is a rectangle
            if ar >= 0.95 and ar <= 1.05:
                shape = "square"
            elif ar <= 0.50:
                shape = "lightbar"
            else:
                shape = "rectangle"
                 
        # if the shape is a pentagon, it will have 5 vertices
        elif len(approx) == 5:
            shape = "pentagon"
 
        # otherwise, we assume the shape is a circle
        else:
            shape = "circle"
 
        # return the name of the shape
        return (shape, approx)

In [134]:
gray = cv2.cvtColor(thresh, cv2.COLOR_BGR2GRAY)

cnts = cv2.findContours(gray, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)
cnts = cnts[0] if imutils.is_cv2() else cnts[1]

for c in cnts:
    try:
        M = cv2.moments(c)
        cX = int((M["m10"] / M["m00"]))
        cY = int((M["m01"] / M["m00"])) 
        
        shape, approx = detect(c)
        print(shape)


        if shape == 'rectangle':
            cv2.drawContours(thresh, [c], -1, (0, 255, 0), 1)
            #cv2.putText(thresh, shape, (cX, cY), cv2.FONT_HERSHEY_SIMPLEX, 0.3, (255, 255, 255), 1)

            (x, y, w, h) = cv2.boundingRect(approx)
            cv2.rectangle(thresh,(x,y),(x+w,y+h),(0,255,0),1)
    except:
        pass
cv2.imshow('Threshold', thresh)

cv2.waitKey(0) # wait until any key is pressed
cv2.destroyAllWindows() # destroy all windows

rectangle
rectangle
rectangle
rectangle
pentagon
